services:
  app:
    build:
      context: .
    container_name: cineposi-admin
    ports:
      - "3001:3000"
    tty: true
    volumes:
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev